package com.database.hibernateannotation.model.key;

import javax.persistence.*;
import java.io.Serializable;

/**
 *
 * This Primary Key is not generated by Hibernate
 * As Hibernate Annotation doesn't support Automatic Generation
 * This Primary Key is generated by
 */
@Entity
@Table(name="EmployeeWithHibernateGeneratedPrimaryKey")
public class EmployeeWithHibernateGeneratedPrimaryKey implements Serializable {
    @Id    //This means Value won't be set by Hibernate
    @Column(name="employee_id")
    private int employeeId;
    @Column(name="employee_name")
    private String employeeName;
    @Column(name="is_active")
    private int isActive;
    @Column(name="data_allowance")
    private long dataAllowance;

    public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public int getIsActive() {
        return isActive;
    }

    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }

    public long getDataAllowance() {
        return dataAllowance;
    }

    public void setDataAllowance(long dataAllowance) {
        this.dataAllowance = dataAllowance;
    }
}
